Repository surendratalk/vigilant-octo-parakeet, pull requests merged in 2022-10, with the labels that each got.

#2 Create css_cheatsheet.md
  css_cheatsheet.md
Labels: help wanted, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#1 Create Python_Cheatsheet.md
  Python_Cheatsheet.md
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#4 Create html_cheatsheet.html
  html_cheatsheet.html
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#7 Create c-sharp.json
  c-sharp.json
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#8 Create java-sheet.md
  java-sheet.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#9 Create css_advanced_cheatsheet.md
  css_advanced_cheatsheet.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#11 Create intel-x86.md
  intel-x86.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
